---
# tasks file for roles/apache
- name: "1) Install package - httpd, mod_ssl"
  yum:
    name:
      - httpd
      - mod_ssl
    state: present
    # 2) Start service - httpd.service
- name: "2) Start service - httpd.service"
  service:
    name: httpd
    state: started
    enabled: yes
 # 3) Configure file - /etc/httpd/index.html.j2
- name: "3) Configure file - /etc/httpd/index.html.j2"
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  
# 4) service on - http, https
- name: "4) service on - http, https"
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
  loop:
    - http
    - https
