---
- name: hosts j2
  gather_facts: yes
  hosts: dev
  tasks:
 #   - name: "create myhosts"
 #     file:
 #      path: /etc/myhosts
 #       state: touch
 #       owner: root
 #      group: root
 #       mode: '0644'
    
    - name: "j2 start"
      template:
        src: template/hosts.j2
        dest: /etc/myhosts
        group: root
        owner: root
        mode: '0644'
